name: ddpg

actor:
  # the learning rate of the actor
  lr: 0.001
  # max norm for clipping actor grads
  max_norm: 0.0
  weight_decay: 0.0
  nan_to_zero: False
  # trunk hidden units
  hidden_size:
    - 256
    - 256
  activation: relu

critic:
  # the learning rate of the critic
  lr: 0.001
  # number of critics (usually 1 or 2 are sufficient)
  ensemble_size: 2
  dropout: 0.0
  # add layer normalization to critic
  layer_norm: False
  # max norm for clipping critic grads
  max_norm: 0.0
  nan_to_zero: False
  weight_decay: 0.0
  # the average coefficient for the critic target update
  tau: 0.005
  # trunk hidden units
  hidden_size:
    - 256
    - 256
  activation: relu
